### ISSUE TITLE
GPG-signed hashes are not properly readable

### ISSUE THREAD

**Issue by lapo-luchini** [Troplo/earl-grey#1]
Signed commits could get some more love in contrast and readability. 😇
<img width="458" alt="image" src="https://github.com/Troplo/earl-grey/assets/420454/bde2f44e-b7e3-4d53-bde6-0e3245d11055">
("broken signatures" should probably show red, but I don't have any handy at the moment)

Oh, it can be easily tested by changing `.isSigned.isVerified` class to `.isSigned.isWarning`:
<img width="225" alt="image" src="https://github.com/Troplo/earl-grey/assets/420454/e0b1ca67-24cd-4cc6-afb4-8e2a902a07b2">

**Comment by Troplo** [comment]
Sorry for the lack of response for a while, I've pushed a commit which should resolve the readability problems across the theme.
![img](https://i.troplo.com/i/ded235503bd1.png)
